### PR TITLE
migrate bootstrap-datepicker to plain rails

### LINKED ISSUE #44: Can't modify frozen String on Foreman 1.24
There have been several reports, that this plugin breaks with Foreman 1.24.

- https://projects.theforeman.org/issues/28375
- https://community.theforeman.org/t/foreman-1-24rc3-cant-modify-frozen-string/16416
- https://community.theforeman.org/t/can-t-modify-frozen-string/16367

### PR DESCRIPTION
**Pull request by timogoebel**
This should fix #44.

### CODE REVIEW

**Comment by laugmanuel** [comment]
It seems to fix the problem for me. 
However the UI is not very pretty - the dropdown is cut after one/two characters which makes reading the values very difficult.

**Comment by timogoebel** [comment]
Currently, there are still some issues with correctly parsing the parameters.

**Comment by timogoebel** [comment]
@laugmanuel: I fixed the remaining issue, mind taking another look?

**Comment by laugmanuel** [comment]
I had a look at the plugin again. Looks good to me now.
I've tested it with Foreman 1.24 RC3 in bulk mode as well as with single hosts.

**Comment by laugmanuel** [comment]
@timogoebel can I support on this?

**Comment by timogoebel** [comment]
@laugmanuel: Thanks, I'm trying to get the tests in #42 to pass since I want to merge this first.

**Comment by timogoebel** [comment]
Test failures were unrelated.

**Comment by laugmanuel** [comment]
Thanks @timogoebel

**Pull request merged**
