### PR TITLE
Use the datepicker component from core

### LINKED ISSUE #52: use the datepicker component from core
Foreman core has a datepicker component which we should use in this plugin, especially after the bootstrap datepicker component was removed in d060046fbe5e4794ab6d463f3aca1b988cac8acb.

https://github.com/theforeman/foreman/tree/develop/webpack/assets/javascripts/react_app/components/common/DateTimePicker

### LINKED ISSUE #69: Forman_expire_hosts on a new Foreman(3.4) installation it trows an error: undefined method `datepicker_f' for
Forman_expire_hosts on a new Foreman(3.4) installation it trows an error:

when:
- Create new host
- Edit existing host

error:
 **undefined method `datepicker_f' for #<ActionView::Base:0x0000000005ab90> Did you mean? datetime_f**

installation:
foreman-installer -v --enable-foreman-plugin-expire-hosts
no errors during/after installation.

trace:
```
2022-11-21T11:12:30 [I|app|1d959f67] Started GET "/hosts/new" for 130.145.199.181 at 2022-11-21 11:12:30 +0100
2022-11-21T11:12:30 [I|app|1d959f67] Processing by HostsController#new as HTML
2022-11-21T11:12:31 [I|app|1d959f67]   Rendered hosts/new.html.erb within layouts/application (Duration: 477.2ms | Allocations: 273581)
2022-11-21T11:12:31 [I|app|1d959f67]   Rendered layout layouts/application.html.erb (Duration: 477.4ms | Allocations: 273636)
2022-11-21T11:12:31 [W|app|1d959f67] undefined method `datepicker_f' for #<ActionView::Base:0x0000000005ab90>
 1d959f67 | Did you mean?  datetime_f
2022-11-21T11:12:31 [I|app|1d959f67] Backtrace for 'undefined method `datepicker_f' for #<ActionView::Base:0x0000000005ab90>
 1d959f67 | Did you mean?  datetime_f' error (ActionView::Template::Error): undefined method `datepicker_f' for #<ActionView::Base:0x0000000005ab90>
 1d959f67 | Did you mean?  datetime_f
 1d959f67 | /usr/share/foreman/app/views/hosts/_form.html.erb:154:in `block (2 levels) in _6e62d1b6d08446df3b4955ffed6e9e2d'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/helpers/form_helper.rb:450:in `form_for'
 1d959f67 | /usr/share/foreman/app/helpers/form_helper.rb:287:in `form_for'
 1d959f67 | /usr/share/foreman/app/views/hosts/_form.html.erb:7:in `block in _6e62d1b6d08446df3b4955ffed6e9e2d'
 1d959f67 | /usr/share/foreman/app/models/taxonomy.rb:80:in `block (2 levels) in as_taxonomy'
 1d959f67 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:195:in `as_location'
 1d959f67 | /usr/share/foreman/app/models/taxonomy.rb:79:in `block in as_taxonomy'
 1d959f67 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:154:in `as_org'
 1d959f67 | /usr/share/foreman/app/models/taxonomy.rb:78:in `as_taxonomy'
 1d959f67 | /usr/share/foreman/app/views/hosts/_form.html.erb:6:in `_6e62d1b6d08446df3b4955ffed6e9e2d'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/base.rb:247:in `public_send'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/base.rb:247:in `_run'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/template.rb:154:in `block in render'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:205:in `instrument'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/template.rb:345:in `instrument_render_template'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/template.rb:152:in `render'
 1d959f67 | /usr/share/gems/gems/deface-1.5.3/lib/deface/action_view_extensions.rb:43:in `render'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `block in instrument'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/partial_renderer.rb:271:in `render'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/renderer.rb:22:in `render'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/base.rb:273:in `in_rendering_context'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/helpers/rendering_helper.rb:34:in `render'
 1d959f67 | /usr/share/foreman/app/views/hosts/new.html.erb:2:in `_f4f8d3d6b5ef4db66e854d34519ebddb'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/base.rb:247:in `public_send'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/base.rb:247:in `_run'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/template.rb:154:in `block in render'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:205:in `instrument'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/template.rb:345:in `instrument_render_template'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/template.rb:152:in `render'
 1d959f67 | /usr/share/gems/gems/deface-1.5.3/lib/deface/action_view_extensions.rb:43:in `render'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `block in instrument'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `block in instrument'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/template_renderer.rb:11:in `render'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/rendering.rb:117:in `block in _render_template'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/base.rb:273:in `in_rendering_context'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/rendering.rb:116:in `_render_template'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/rendering.rb:103:in `render_to_body'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/abstract_controller/rendering.rb:25:in `render'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/rendering.rb:36:in `render'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
 1d959f67 | /usr/share/ruby/benchmark.rb:308:in `realtime'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
 1d959f67 | /usr/share/gems/gems/activerecord-6.1.6.1/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:45:in `render'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/abstract_controller/base.rb:228:in `process_action'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 1d959f67 | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 1d959f67 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 1d959f67 | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 1d959f67 | /usr/share/gems/gems/audited-4.10.0/lib/audited/sweeper.rb:14:in `around'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 1d959f67 | /usr/share/gems/gems/audited-4.10.0/lib/audited/sweeper.rb:14:in `around'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `block in instrument'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
 1d959f67 | /usr/share/gems/gems/activerecord-6.1.6.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/abstract_controller/base.rb:165:in `process'
 1d959f67 | /usr/share/gems/gems/actionview-6.1.6.1/lib/action_view/rendering.rb:39:in `process'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal.rb:190:in `dispatch'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_controller/metal.rb:254:in `dispatch'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:32:in `each'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:32:in `serve'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:842:in `call'
 1d959f67 | /usr/share/gems/gems/katello-4.6.0/lib/katello/middleware/organization_created_enforcer.rb:18:in `call'
 1d959f67 | /usr/share/gems/gems/katello-4.6.0/lib/katello/middleware/event_daemon.rb:10:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/apipie-dsl-2.5.0/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 1d959f67 | /usr/share/gems/gems/apipie-rails-0.5.20/lib/apipie/static_dispatcher.rb:66:in `call'
 1d959f67 | /usr/share/gems/gems/apipie-rails-0.5.20/lib/apipie/extractor/recorder.rb:137:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/foreman/lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
 1d959f67 | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 1d959f67 | /usr/share/gems/gems/apipie-rails-0.5.20/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/conditional_get.rb:27:in `call'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
 1d959f67 | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/cookies.rb:689:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 1d959f67 | /usr/share/gems/gems/railties-6.1.6.1/lib/rails/rack/logger.rb:37:in `call_app'
 1d959f67 | /usr/share/gems/gems/railties-6.1.6.1/lib/rails/rack/logger.rb:28:in `call'
 1d959f67 | /usr/share/gems/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 1d959f67 | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 1d959f67 | /usr/share/gems/gems/katello-4.6.0/lib/katello/prevent_json_parsing.rb:12:in `call'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
 1d959f67 | /usr/share/gems/gems/activesupport-6.1.6.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/ssl.rb:77:in `call'
 1d959f67 | /usr/share/gems/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
 1d959f67 | /usr/share/gems/gems/secure_headers-6.3.4/lib/secure_headers/middleware.rb:11:in `call'
 1d959f67 | /usr/share/gems/gems/railties-6.1.6.1/lib/rails/engine.rb:539:in `call'
 1d959f67 | /usr/share/gems/gems/railties-6.1.6.1/lib/rails/railtie.rb:207:in `public_send'
 1d959f67 | /usr/share/gems/gems/railties-6.1.6.1/lib/rails/railtie.rb:207:in `method_missing'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/urlmap.rb:74:in `block in call'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/urlmap.rb:58:in `each'
 1d959f67 | /usr/share/gems/gems/rack-2.2.4/lib/rack/urlmap.rb:58:in `call'
 1d959f67 | /usr/share/gems/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'
 1d959f67 | /usr/share/gems/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'
 1d959f67 | /usr/share/gems/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 1d959f67 | /usr/share/gems/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'
 1d959f67 | /usr/share/gems/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'
 1d959f67 | /usr/share/gems/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
 1d959f67 | /usr/share/gems/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2022-11-21T11:12:31 [I|app|1d959f67]   Rendered common/500.html.erb within layouts/application (Duration: 6.8ms | Allocations: 6633)
2022-11-21T11:12:31 [I|app|1d959f67]   Rendered layouts/base.html.erb (Duration: 7.6ms | Allocations: 9266)
2022-11-21T11:12:31 [I|app|1d959f67]   Rendered layout layouts/application.html.erb (Duration: 22.9ms | Allocations: 27854)
2022-11-21T11:12:31 [I|app|1d959f67] Completed 500 Internal Server Error in 517ms (Views: 23.5ms | ActiveRecord: 28.9ms | Allocations: 305915)

Foreman version: 3.4.0
Plugins: 
 - foreman-tasks 7.0.0
 - foreman_ansible 9.0.1
 - foreman_bootdisk 21.0.2
 - foreman_expire_hosts 8.0.0
 - foreman_leapp 0.1.10
 - foreman_puppet 4.0.1
 - foreman_remote_execution 8.0.0
 - foreman_snapshot_management 2.0.1
 - foreman_templates 9.2.0
 - foreman_virt_who_configure 0.5.9
 - foreman_webhooks 3.0.5
 - katello 4.6.0
```

### PR DESCRIPTION
**Pull request by kamils-iRonin**
fixes #52, fixes #69

image

### CODE REVIEW

**Comment by timogoebel** [comment]
Nice. We don‘t need a timepicker, the date is enough. And we also have another datepicker in the multiple action. :-)

**Comment by kamils-iRonin** [comment]
waiting for https://github.com/theforeman/foreman/pull/7404 and https://github.com/theforeman/foreman/pull/7406

**Comment by timogoebel** [comment]
The whole idea was to get rid of deface eventually. I'm wondering if we can add a helper (that calls `mount_react_component`?) in core so we don't need to use deface here.

**Comment by kamils-iRonin** [comment]
> The whole idea was to get rid of deface eventually

actually, we don't need deface if we add the `DatePicker` component to the component registry in core, I don't know why this component is not added there

**Comment by timogoebel** [comment]
I think we should add it there. That’s a no-brainer inho.

**Comment by kamils-iRonin** [comment]
image
image

**Comment by timogoebel** [comment]
@kamils-iRonin: Do you mind bumping the minimum required Foreman version in `engine.rb`?

**Comment by timogoebel** [comment]
@kamils-iRonin: This needs a rebase, now.

**Comment by kamils-iRonin** [comment]
@timogoebel rebased

**Comment by laugmanuel** [comment]
Hi @kamils-iRonin ,
I just had a look at this and in general this works nicely!
I've just noticed that I don't see an error message on the GUI if I select a date in the past. The console however shows:
```
09:14:07 rails.1   | 2021-02-10T09:14:07 [E|app|a03d3c5f] Failed to save: Expired on must be in the future
```
I've tested with `Foreman 2.5.0-develop`.  Can you verify this or is it a local problem?

**Comment by ekohl** [comment]
@kamils-iRonin can you rebase this now that I've merged the CI pipeline fixes?

**Review by ekohl — APPROVED** [review]
I'm going to trust you on the implementation since I didn't test it, but it looks sane and it's broken now anyway.

**Pull request merged**
