### PR TITLE
add edit_host_expiry permission

### LINKED ISSUE #6: No possibility to set permissions
Since Foreman 1.13 you can set permissions for everything and filter them.
To use your Plugin I have to be Administrator, otherwise I do not have the permissions even when I'm allowed to do everything else e.g. deleting a host.
Is there any possibility to add this?

### PR DESCRIPTION
**Pull request by timogoebel**
Fixes #6.

### CODE REVIEW

**Comment by Alucard616** [comment]
We finally tested this.
It works perfectly fine :)

**Comment by Alucard616** [comment]
Please merge :)

**Comment by timogoebel** [comment]
@Alucard616 : Thanks for testing this. I really appreciated it. I'm planning on doing this later today. I'll release a new version that includes these changes as well.

**Comment by Alucard616** [comment]
Thank you very much :)

**Pull request merged**
