### PR TITLE
Fix Change Expiration action

### LINKED ISSUE #61: Invalid expiration date upon multiple hosts expiration date change
Hello,
after upgrade Foreman to 1.24.3 and foreman_expire_hosts plugin to 7.0.0 we cannot update expiration date of hosts with "select action" button and getting "Invalid expiration date!" error.
Change of expiration date from host's properties is working as usual.

In logs we got only following with loglevel=debug:

> 2020-06-02T15:31:25 [I|app|3718ea40] Started POST "/expired_hosts/select_multiple_expiration" for 10.101.186.18 at 2020-06-02 15:31:25 +0300
2020-06-02T15:31:25 [I|app|3718ea40] Processing by HostsController#select_multiple_expiration as HTML
2020-06-02T15:31:25 [I|app|3718ea40]   Parameters: {"host_ids"=>["35", "38"]}
2020-06-02T15:31:25 [D|tax|3718ea40] Current location set to SANDBOX/CDT
2020-06-02T15:31:25 [D|tax|3718ea40] Current organization set to Default Organization
2020-06-02T15:31:25 [I|app|3718ea40]   Rendering /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_expire_hosts-7.0.0/app/views/hosts/select_multiple_expiration.html.erb within layouts/application
2020-06-02T15:31:25 [I|app|3718ea40]   Rendered hosts/_selected_hosts.html.erb (217.4ms)
2020-06-02T15:31:25 [I|app|3718ea40]   Rendered /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_expire_hosts-7.0.0/app/views/hosts/select_multiple_expiration.html.erb within layouts/application (649.3ms)
2020-06-02T15:31:25 [I|app|3718ea40]   Rendered layouts/_application_content.html.erb (2.0ms)
2020-06-02T15:31:25 [I|app|3718ea40]   Rendering layouts/base.html.erb
2020-06-02T15:31:25 [I|app|3718ea40]   Rendered layouts/base.html.erb (39.6ms)
2020-06-02T15:31:25 [I|app|3718ea40] Completed 200 OK in 738ms (Views: 687.2ms | ActiveRecord: 18.7ms)
2020-06-02T15:31:37 [I|app|3eb5a718] Started POST "/expired_hosts/update_multiple_expiration?host_ids%5B%5D=35&host_ids%5B%5D=38" for 10.101.186.18 at 2020-06-02 15:31:37 +0300
2020-06-02T15:31:37 [I|app|3eb5a718] Processing by HostsController#update_multiple_expiration as HTML
2020-06-02T15:31:37 [I|app|3eb5a718]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"<sanitized>", "host"=>{"expired_on(1i)"=>"2021", "expired_on(2i)"=>"1", "expired_on(3i)"=>"1"}, "host_ids"=>["35", "38"]}
2020-06-02T15:31:37 [D|tax|3eb5a718] Current location set to SANDBOX/CDT
2020-06-02T15:31:37 [D|tax|3eb5a718] Current organization set to Default Organization
2020-06-02T15:31:37 [I|app|3eb5a718] Redirected to https://10.101.106.14/hosts
2020-06-02T15:31:37 [I|app|3eb5a718] Filter chain halted as :validate_multiple_expiration rendered or redirected
2020-06-02T15:31:37 [I|app|3eb5a718] Completed 302 Found in 11ms (ActiveRecord: 1.7ms)

### PR DESCRIPTION
**Pull request by kamils-iRonin**
fix #61

### CODE REVIEW

**Comment by timogoebel** [comment]
@vladimirsafronov1251: Do you mind testing this patch?

**Comment by kamils-iRonin** [comment]
[test foreman_expire_hosts]

**Comment by vladimirsafronov1251** [comment]
@timogoebel , @kamils-iRonin, it works, thank you!

**Comment by laugmanuel** [comment]
@kamils-iRonin, @timogoebel I've just noticed that we have the same problem in our environment. Will apply the patch manually and report back later.

Edit: Successfully tested this. I think we can merge this!

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks!

**Pull request merged**
